### ISSUE TITLE
DWA-131 Revision E tested

### ISSUE THREAD

**Issue by haw0k** [ZeeRooo/RTL8192EU#12]
Ubuntu 18.04 with kernel 4.15.0-58-generic and kernel 4.15.0-55-generic
This driver successfully builded, installed  and worked with D-Link DWA-131 Revision E USB stick.
Please add to documentation this command:
`sudo apt install libelf-dev`
because without libelf-dev you can't build .ko file from sources

**Comment by ZeeRooo** [comment]
Thank you for the observation. I have modified the readme.
